-- 本文件由 ../Templates/Sql/Mysql/DropTables.sql.tpl 生成；请勿手改，改动请改模板后重跑 pumpall.py
DROP TABLE IF EXISTS `t_TradingDay`;
DROP TABLE IF EXISTS `t_Exchange`;
DROP TABLE IF EXISTS `t_Product`;
DROP TABLE IF EXISTS `t_Instrument`;
DROP TABLE IF EXISTS `t_PrimaryAccount`;
DROP TABLE IF EXISTS `t_Account`;
DROP TABLE IF EXISTS `t_Capital`;
DROP TABLE IF EXISTS `t_Position`;
DROP TABLE IF EXISTS `t_PositionDetail`;
DROP TABLE IF EXISTS `t_Order`;
DROP TABLE IF EXISTS `t_Trade`;
